export const ITEM_STATUS_REQUEST = 'ITEM_STATUS_REQUEST';
export const ITEM_STATUS_SUCCESS = 'ITEM_STATUS_SUCCESS';
export const ITEM_STATUS_FAIL = 'ITEM_STATUS_FAIL';

export const ITEM_ADD_REQUEST = 'ITEM_ADD_REQUEST';
export const ITEM_ADD_SUCCESS = 'ITEM_ADD_SUCCESS';
export const ITEM_ADD_FAIL = 'ITEM_ADD_FAIL';

export const ITEM_UPDATE_REQUEST = 'ITEM_UPDATE_REQUEST';
export const ITEM_UPDATE_SUCCESS = 'ITEM_UPDATE_SUCCESS';
export const ITEM_UPDATE_FAIL = 'ITEM_UPDATE_FAIL';

export const ITEMLIST_ADD_REQUEST = 'ITEMLIST_ADD_REQUEST';
export const ITEMLIST_ADD_SUCCESS = 'ITEMLIST_ADD_SUCCESS';
export const ITEMLIST_ADD_FAIL = 'ITEMLIST_ADD_FAIL'




